### PR TITLE
Grouped import routes, js files, and styles together to organize

### PR DESCRIPTION
**Pull request by chitrarajavel**
I fixed suggested changes on organizations, added folders for a clean look, and changed userObj to isAuthenticated per suggestions. I haven't fixed {  users: [],  favorites: [] } yet. I will work on it tomorrow. Indentation is currently set to 4 in my prettier. I will fix it toward the end of the project.

### CODE REVIEW

**Comment by dondrzzy** [comment]
When you get feedback on a pull request, you address that and push it to the same feature branch so there is a proper trail for your team that may be looking into this now or later. We can do two things
- The easiest is to merge this branch into `main-with-routes` and review those changes there
- pull these changes locally into `main-with-route` and you push them. Might be a little complex for now (but a good learning experience) but would require dropping that last merge commit that seems to be adding contradicting changes in 2 files. 

Let me know which method you prefer.

**Comment by dondrzzy** [comment]
Secondly do not write your commit messages as `fixed requested changes` because that does not make much sense. but rather, `feat: created login component`, `fix: removed header from page`, `fix: added button to payment form`, `chore: added coverage reporting package` etc

**Comment by chitrarajavel** [comment]
Hi Donald,

I pulled the branches locally and merged them. I haven't pushed them to
GitHub yet. Maybe we can do that tomorrow during our meeting.

Thanks,
Chitra

**Review by dondrzzy — APPROVED** [review]
lgtm, 🚀

**Pull request merged**
